In [4]:
import numpy as np

In [6]:
a = np.array([1,2,3])

In [8]:
print(a)

[1 2 3]


In [43]:
b = np.zeros((2,3,4))

In [44]:
print(b)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [18]:
c = np.ones((2,3,4),dtype=np.int16)

In [19]:
print(c)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [25]:
d = np.arange(10,25,6)

In [26]:
print(d)

[10 16 22]


In [27]:
e = np.linspace(0,2,9)

In [28]:
print(e)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [29]:
f = np.full((2,2),7)
print(f)

[[7 7]
 [7 7]]


In [30]:
g = np.eye(2)
print(g)

[[1. 0.]
 [0. 1.]]


In [32]:
h = np.random.random((3,3))
print(h)

[[0.22261615 0.51963396 0.82968157]
 [0.48047459 0.1219099  0.07850338]
 [0.55028373 0.93269586 0.66681927]]


In [33]:
i = np.empty((3,2))
print(i)

[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


In [34]:
i.shape

(3, 2)

In [35]:
len(c)

2

In [36]:
len(d)

3

In [37]:
i.ndim

2

In [38]:
i.size

6

In [39]:
i.dtype

dtype('float64')

In [40]:
i.dtype.name

'float64'

In [41]:
i.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
j = c-b
print(j)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [46]:
j.dot

<function ndarray.dot>