# welcome to numpy tut

In [4]:
import sklearn

In [5]:
import numpy as np

In [6]:
print('hello')

hello


In [23]:
myarr = np.array([[3,6,32,34,7]],  np.int64)

In [24]:
myarr[0,1]

6

In [26]:
myarr = np.array([3,6,32,34,7],  np.int64)

In [27]:
myarr[0]

3

In [28]:
myarr.shape

(5,)

In [29]:
myarr.dtype

dtype('int64')

In [30]:
myarr[1] = 45

In [31]:
myarr

array([ 3, 45, 32, 34,  7], dtype=int64)

# Array creation: Converstion from other Python structures

In [32]:
listarray = np.array([[1,2,3] , [5,6,7] , [24,6,6]])

In [33]:
listarray

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [24,  6,  6]])

In [34]:
listarray.shape

(3, 3)

In [35]:
listarray.size

9

In [36]:
np.array({2,4,5})

array({2, 4, 5}, dtype=object)

In [37]:
arr1 = np.zeros((2,3))

In [38]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
rng = np.arange(10)

In [45]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
lspace = np.linspace(1,100,10)

In [59]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [64]:
emp = np.empty((4,3))


In [65]:
emp

array([[1.23164770e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.10343781e-312, 2.02456523e-052],
       [8.15943809e-043, 1.25790665e-047, 6.59452305e-066],
       [8.75706806e+169, 1.44105406e+160, 9.30265869e+165]])

In [66]:
emp_like = np.empty_like(lspace)

In [67]:
emp_like

array([1.23164770e-311, 3.16202013e-322, 1.10343781e-312, 2.02456523e-052,
       8.15943809e-043, 1.25790665e-047, 6.59452305e-066, 8.75706806e+169,
       1.44105406e+160, 9.30265869e+165])

In [68]:
ide = np.eye(4)

In [69]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
ide.shape


(4, 4)

In [71]:
arr = np.arange(100)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
arr.size

100

In [76]:
arr.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
arr = arr.reshape(10,10)

In [81]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
arr = arr.ravel()

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [86]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [87]:
ar = np.array(x)

In [88]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
ar.sum(axis=0)

array([12, 15, 18])

In [90]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [91]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [92]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [93]:
ar.ndim

2

In [94]:
ar.size

9

In [95]:
ar.nbytes

36

In [97]:
br = np.ones([3,3])

In [98]:
br

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
one1.argmax()

NameError: name 'one1' is not defined

In [107]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
ar.argmax()

8

In [110]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [111]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
ar = ar.ravel()

In [113]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
ar.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [115]:
ar.argmin()

0

In [117]:
ar = ar.reshape(3,3)

In [118]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
ar1 = ar

In [120]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
ar1 = ar.T

In [122]:
ar1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [123]:
ar + ar1

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [124]:
ar * ar1

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [125]:
np.sqrt(ar1)

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 2.82842712],
       [1.73205081, 2.44948974, 3.        ]])

In [126]:
ar1.sum()

45

In [128]:
ar.sum()

45

In [132]:
type(np.where(ar>6))

tuple

In [133]:
np.count_nonzero(ar1)

9

In [134]:
import sys

In [135]:
ch_ar = [0,4,55,2]

In [136]:
np_ar = np.array(ch_ar)

In [137]:
sys.getsizeof(1) * len(ch_ar)

112